# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Role.create(name: 'admin')
User.create(name: 'admin', email: 'admin@magicbeans.com', ic: '910203-10-5123', phone: '0145667896', password: 'password', password_confirmation: 'password', confirmed_at: Time.now)
Log.create(title: 'Created a user', log_type: 'users', type_id: 1)
User.find_by_id(1).roles.push(Role.find_by_name('admin'))
Log.create(title: 'Updated a user', log_type: 'users', type_id: 1)
Program.create(name: 'MaGIC Techinical Bootcamps', description: "As part of MaGIC Academy, we are offering several full-time coding and design bootcamps with the goal to increase the number of technical founders, and the pool of qualified technical employees and designers.", speaker: 'Various Instructors', speakerbio: 'Web/Rails Developer', biourl: 'www.mymagic.my/technicalbootcamp/#team', keytakeways: 'Learn Web Development', resources: "www.mymagic.my")
Log.create(title: 'Created a program', log_type: 'programs', type_id: 1)
Program.create(name: 'MaGIC – Stanford Go2Market Program', description: "Calling all aspiring entrepreneurs who are looking to commercialize your intellectual property, ideas and research! Stanford Graduate School of Business is coming to Malaysian Global Innovation & Creativity Centre (MaGIC) for a one-week Go2Market program that helps you take the leap from being an innovator with an idea to becoming an entrepreneur with a business. Taught by the same faculty who teach in Stanford MBA program, the Go2Market program will expose participants to leading-edge knowledge and frameworks in the areas such as business model strategy, pricing, accounting, marketing, go-to-market strategy, and pitching to investors. The end goal is to help you fully develop your go-to-market plan, as well as your pitching skills.", speaker: 'Stanford Graduate School of Business', speakerbio: 'Faculty who teach in Stanford MBA program', biourl: 'www.gsb.stanford.edu/', keytakeways: 'Launch their product/service in the market.', resources: "www.mymagic.my/programs/stanfordgo2market/")
Log.create(title: 'Created a program', log_type: 'programs', type_id: 2)
Program.create(name: 'MaGIC-Hub Social Entrepreneurship Bootcamp', description: "Experience the INSEAD Entrepreneurship Bootcamp™ used widely for MBA students. Find team members and mentors. Pitch to real impact investors, fund managers and philanthropists in a safe environment. Get inspired and obtain feedback from peers. In just one weekend, equip yourself to start a sustainable business to meet a neglected social need.", speaker: 'Grace Sai, Raya Papp', speakerbio: 'Co-Founder - The Hub Singapore, Co-Head Asia Pacific - LGT Venture Philanthropy', biourl: 'www.mymagic.my/programs/sebootcamp/', keytakeways: 'From idea to social impact venture in just 48 hours', resources: "www.mymagic.my/programs/sebootcamp/")
Log.create(title: 'Created a program', log_type: 'programs', type_id: 3)
Activity.create(name: 'Web Development Bootcamp',start_date: DateTime.new(2015,3,1,9,0,0,'+8'), end_date: DateTime.new(2015,5,31,5,0,0,'+8'),venue: 'MaGIC Headquarter',description: "Whether you are a recent graduate, a non-technical founder or a career-switcher, you can become a highly-skilled web developer. Our 9 week long full time web development class takes you from zero to hero. When you complete it, you'll have all the skills needed to rapidly deploy your visions. The next intake in November is already full. Apply NOW for the next intake. Slots are limited and they are going fast. When you graduate, you may go directly to work as a web developer or continue with one of our other excellent training programs.",speaker: 'Various Instructors',speakerbio: 'Web/Rails Developer',biolink: 'www.codedivision.my/#team',keytakeaway: 'Learn Web Dev',prerequisite: 'NIL', maxattendee: 5,resources: "www.codedivision.my",program_id: 1)
Log.create(title: 'Created an activity', log_type: 'activities', type_id: 1)
Activity.create(name: 'Programmer Finishing School',start_date: DateTime.new(2015,3,1,9,0,0,'+8'), end_date: DateTime.new(2015,5,31,5,0,0,'+8'),venue: 'Makespace, SSTwo Mall',description: "Are you a final year computer science/engineering student? We'll coach you both on-site and remotely to polish your communication, collaboration and web development skills. You'll work as part of a team to design, build, test and deploy an MVP application for a startup. And your work counts as your final year project. Do well, and your startup might just ask you to stick around after graduation. Or gain the upper hand in the competitive job market for highly paid tech jobs. Apply NOW for the next intake in early 2015. Limited slots available.",speaker: 'Various Instructors',speakerbio: 'Rails Developer',biolink: 'www.codemalaysia.com/#footer',keytakeaway: 'Learn Rails',prerequisite: 'NIL', maxattendee: 30,resources: "www.codemalaysia.com",program_id: 1)
Log.create(title: 'Created an activity', log_type: 'activities', type_id: 2)
Activity.create(name: 'Developer & Design Apprenticeship',start_date: DateTime.new(2015,3,1,9,0,0,'+8'), end_date: DateTime.new(2015,8,31,5,0,0,'+8'),venue: 'SSTwo Mall, Seksyen 17',description: 'Throughout this six-month program, senior developers or designers guide you as you work on multiple startup projects of varying difficulty. You learn by doing to equip you with skills to join a startup as a mid-to-senior level developer or designer when you graduate. Slots for this program are very limited so be sure to enroll as soon as possible. Application continues through March 2015.',speaker: 'Various Instructors',speakerbio: 'Web Developer/Designer',biolink: 'www.joinalps.com',keytakeaway: 'Learn Web Development/Designer',prerequisite: 'Web Development/Design Background', maxattendee: 5,resources: "www.joinalps.com/apprentices",program_id: 1)
Log.create(title: 'Created an activity', log_type: 'activities', type_id: 3)
Activity.create(name: 'MaGIC-Hub Social Entrepreneurship Bootcamp', start_date: DateTime.new(2015,9,17,9,0,0,'+8'), end_date: DateTime.new(2015,9,19,5,0,0,'+8'),venue: 'MaGIC Campus', description: "Experience the INSEAD Entrepreneurship Bootcamp™ used widely for MBA students. Find team members and mentors. Pitch to real impact investors, fund managers and philanthropists in a safe environment. Get inspired and obtain feedback from peers. In just one weekend, equip yourself to start a sustainable business to meet a neglected social need.", speaker: 'Grace Sai, Raya Papp', speakerbio: 'Co-Founder - The Hub Singapore, Co-Head Asia Pacific - LGT Venture Philanthropy', biolink: 'www.mymagic.my/programs/sebootcamp/', keytakeaway: 'From idea to social impact venture in just 48 hours', prerequisite: 'nil', maxattendee: 100, resources: "www.mymagic.my/programs/sebootcamp/", program_id: 2)
Log.create(title: 'Created an activity', log_type: 'activities', type_id: 4)
Activity.create(name: 'MaGIC – Stanford Go2Market Program', start_date: DateTime.new(2015,3,15,9,0,0,'+8'), end_date: DateTime.new(2015,3,20,5,0,0,'+8'), venue: 'MaGIC Campus', description: "Calling all aspiring entrepreneurs who are looking to commercialize your intellectual property, ideas and research! Stanford Graduate School of Business is coming to Malaysian Global Innovation & Creativity Centre (MaGIC) for a one-week Go2Market program that helps you take the leap from being an innovator with an idea to becoming an entrepreneur with a business. Taught by the same faculty who teach in Stanford MBA program, the Go2Market program will expose participants to leading-edge knowledge and frameworks in the areas such as business model strategy, pricing, accounting, marketing, go-to-market strategy, and pitching to investors. The end goal is to help you fully develop your go-to-market plan, as well as your pitching skills.", speaker: 'Stanford Graduate School of Business', speakerbio: 'Faculty who teach in Stanford MBA program', biolink: 'www.gsb.stanford.edu/', keytakeaway: 'Launch their product/service in the market.', prerequisite: 'nil', maxattendee: 50, resources: "www.mymagic.my/programs/stanfordgo2market/", program_id: 3)
Log.create(title: 'Created an activity', log_type: 'activities', type_id: 5)